server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.173.12:3306/pig-chat
    username: root
    password: '@Aa123456'
  redis:
    database: 0
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    username: flying_pig_z@qq.com
    password:
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
        debug: true
#持久层配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true